server:
  port: 8081

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: ${nebula.datasource.driver-class-name}
    url: ${nebula.datasource.url}
    username: ${nebula.datasource.username}
    password: ${nebula.datasource.password}
  data:
    redis:
      host: ${nebula.redis.host}
      port: ${nebula.redis.port}
      database: ${nebula.redis.database}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

login-reg:
  jwt:
    employee-secret-key: cyh_handsome
    employee-ttl: 864000000
    employee-token-name: Authorization
    user-secret-key: user_handsome
    user-ttl: 864000000
    user-token-name: Authorization

nebula:
  wechat:
    appid: ${nebula.wechat.appid}
    secret: ${nebula.wechat.secret}

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: cyh_handsome
    # 设置jwt过期时间
    admin-ttl: 86400000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: user_handsome
    user-ttl: 86400000
    user-token-name: authentication

  shop:
    address: ZhengZhou University
  baidu:
    ak: ePMydufnJzBBTQlrzKwxAmlpRApLxmOW